### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by itechsen** [ox01024/Z790M-AORUS-ELITE-I7-13700k-OpenCore-Hackintosh#1]
改了三码，进入opencore选项选择U盘安装，直接黑屏

**Comment by ox01024** [comment]
换成Debug 版本的 Oc使用  -v模式 看看日志

**Comment by itechsen** [comment]
打开啰嗦模式，日志是说无法找到dmg，config默认隐藏了读取dmg.现在已经搞定了。感谢提醒。还有一个问题，因为我的u是13600kf，我也用cpufriend重新定制了我u的文件，但是跑分还是异常，比正常分低20-30%，不知道是什么问题

**Comment by ox01024** [comment]
https://www.bilibili.com/video/BV1yR4y1C75v/?spm_id_from=333.999.0.0&vd_source=18c1d4aa15248f11c44f420fc80e1f0a 看下这个有不同的驱动方式的跑分对比选择一个合适你的就行
