### ISSUE TITLE
睡眠后唤醒问题

### ISSUE THREAD

**Issue by itechsen** [ox01024/Z790M-AORUS-ELITE-I7-13700k-OpenCore-Hackintosh#2]
睡眠后唤醒无信号黑屏，尝试开关显示器可以显示了，但是蓝牙挂了，蓝牙开关按钮也无法正常使用。。。

**Comment by ox01024** [comment]
是 （奋威 T919） 这款吗 没遇到过

**Comment by itechsen** [comment]
> 是 （奋威 T919） 这款吗 没遇到过

对的。 而且我发现USB定制的时候，背后那个typeC口没有定制进去。无法正常使用

**Comment by ox01024** [comment]
可能是我没用到那个接口没碰到
